### ISSUE TITLE
Mobile - Map.onClick event not fire

### ISSUE THREAD

**Issue by lokhmakov** [mariusandra/pigeon-maps#22]

**Comment by mariusandra** [comment]
I guess this was fixed with PR #20 ?

**Comment by ccMatrix** [comment]
Nope, the PR #20 did not fix this since the onClick method is never called. From my initial tests you will have to trigger onClick if the touch coords are inside the click tolerance. 

```
            const pixel = this.map.getMousePixel(this.map._containerRef, touch);
            if (
              Math.abs(oldTouchCoords[0] - newTouchCoords[0]) > this.map.CLICK_TOLERANCE
              || Math.abs(oldTouchCoords[1] - newTouchCoords[1]) > this.map.CLICK_TOLERANCE
            ) {
              event.preventDefault();
              this.map.throwAfterMoving(pixel, center, zoom);
            }
            else if (this.map.props.onClick) {
              event.preventDefault();
              const latLng = this.map.pixelToLatLng(pixel);
              this.map.props.onClick({ event, latLng, pixel });
            }
```

**Comment by w0wka91** [comment]
I have also trouble with the onClick handler on iOS devices. It's working all fine on desktop browsers (Safari, Chrome, Firefox) and android (Chrome) but its not working on the iOS default browser. Did anyone had the same experience?
